// <auto-generated />
namespace CAP_Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FSTITransactionkeyaddedtoTicketcounttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FSTITransactionkeyaddedtoTicketcounttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711272152576_FSTI Transaction key added to Ticket count table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
