// <auto-generated />
namespace CAP_Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Motagcountcompdesc50to150 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Motagcountcompdesc50to150));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091702314_Mo tag count comp desc 50 to 150"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
