// <auto-generated />
namespace CAP_Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V_FSTI_TransactionviewSupportadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V_FSTI_TransactionviewSupportadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201712120135262_V_FSTI_Transaction [view] Support added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
