// <auto-generated />
namespace CAP_Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fginwipfieldaddtoMOTagheader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fginwipfieldaddtoMOTagheader));
        
        string IMigrationMetadata.Id
        {
            get { return "201709290138468_fg in wip field add to MO Tag header"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
