// <auto-generated />
namespace CAP_Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MOtagheaderParent_Item_Desclength50to100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MOtagheaderParent_Item_Desclength50to100));
        
        string IMigrationMetadata.Id
        {
            get { return "201710012318111_MOtag header Parent_Item_Desc length 50 to 100"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
