// <auto-generated />
namespace CAP_Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LocationMassterTableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocationMassterTableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201801052054086_Location Masster Table added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
